const pages = {
  artists: "Artists",
  artistEditor: "ArtistEditor",
  genres: "Genres",
  genreEditor: "GenreEditor",
  wishlistArtists: "WishlistArtists",
  albums: "Albums",
  albumEditor: "AlbumEditor",
  albumPurchaseDetails: "AlbumPurchaseDetails",
  albumPicker: "AlbumPicker",
  wishlistAlbums: "WishlistAlbums",
  tracks: "Tracks",
  trackEditor: "TrackEditor",
  retailers: "Retailers",
  retailerDetails: "RetailerDetails",
  retailerEditor: "RetailerEditor",
  equipmentTypes: "EquipmentTypes",
  equipmentTypeEditor: "EquipmentTypeEditor",
  manufacturers: "Manufacturers",
  manufacturerEditor: "ManufacturerEditor",
  equipment: "Equipment",
  equipmentEditor: "EquipmentEditor",
  equipmentPurchaseDetails: "EquipmentPurchaseDetails",
  lookup: "Lookup",
  export: "Export",
  artistStatisticsReport: "ArtistStatisticsReport",
  genreStatisticsReport: "GenreStatisticsReport",
  genreAlbumsReport: "GenreAlbumsReport",
  jobStatusReport: "JobStatusReport",
  monthlySpendReport: "MonthlySpendReport",
  retailerStatisticsReport: "RetailerStatisticsReport",
  albumsByPurchaseDateReport: "AlbumsByPurchaseDateReport",
  moods: "Moods",
  moodEditor: "MoodEditor",
  artistMoodEditor: "ArtistMoodEditor",
  closestArtists: "ClosestArtists",
  playlistBuilder: "PlaylistBuilder",
  savedSessions: "SavedSessions",
  savedSessionDetails: "SavedSessionDetails"
};

export default pages;
