const pages = {
  artists: "Artists",
  artistEditor: "ArtistEditor",
  genres: "Genres",
  wishlistArtists: "WishlistArtists",
  albums: "Albums",
  albumEditor: "AlbumEditor",
  wishlistAlbums: "WishlistAlbums",
  tracks: "Tracks",
  trackEditor: "TrackEditor",
  retailers: "Retailers",
  retailerDetails: "RetailerDetails",
  retailerEditor: "RetailerEditor",
  equipmentTypes: "EquipmentTypes",
  equipmentTypeEditor: "EquipmentTypeEditor",
  manufacturers: "Manufacturers",
  manufacturerEditor: "ManufacturerEditor",
  equipment: "Equipment",
  equipmentEditor: "EquipmentEditor",
  lookup: "Lookup",
  export: "Export",
  artistStatisticsReport: "ArtistStatisticsReport",
  genreStatisticsReport: "GenreStatisticsReport",
  jobStatusReport: "JobStatusReport",
  monthlySpendReport: "MonthlySpendReport",
  retailerStatisticsReport: "RetailerStatisticsReport",
  albumPurchaseDetails: "AlbumPurchaseDetails",
};

export default pages;
